spring:
  application:
    name: student-config-server
  cloud:
    config:
      server:
        git:
          uri: file://D:\\workspace\\student-config-repo
          search-paths:
          - student-detail-service
          - student-client
          - eureka-naming-server
server:
  port: 8888    